---
title: '0506'
author: '106035070'
date: "2019年5月6日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#作業1

# 1.0 Load libraries ----
```{r}
library(tidyverse)
library(lubridate)
library(tidyquant)
library(readxl)
library(writexl)
```
# 2.0 Importing Files ----
```{r}
bikes_tbl <- read_excel("bikes.xlsx")
bikeshops_tbl <- read_excel("bikeshops.xlsx")
orderlines_tbl <- read_excel("orderlines.xlsx")
```
# 3.0 Examining Data ----
```{r}
bikes_tbl
orderlines_tbl %>% glimpse()
```
# 4.0 Joining Data ----
```{r}
left_join(orderlines_tbl, bikes_tbl, by = c("product.id" = "bike.id"))

orderlines_bikes_tbl <- orderlines_tbl %>% left_join(bikes_tbl, by = c("product.id"= "bike.id")) %>% left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

orderlines_tbl %>% left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>% 
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

bikes_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

bikes_orderlines_joined_tbl

bikes_orderlines_joined_tbl %>% glimpse()
```
# 5.0 Wrangling Data ----
```{r}
bikes_orderlines_wrangled_tbl <- bikes_orderlines_joined_tbl %>%
  
  # Separate description into category.1, category.2, and frame.material
  separate(description,
           into = c("category.1", "category.2", "frame.material"),
           sep = " - ",
           remove = TRUE) %>%
  
  # Separate location into city and state
  separate(location,
           into = c("city", "state"),
           sep  = ", ",
           remove = FALSE) %>%
  
  # price extended
  mutate(total.price = price * quantity) %>%
  
  # Reorganize
  select(-1, -location) %>%
  select(-ends_with(".id")) %>%
  
  bind_cols(bikes_orderlines_joined_tbl %>% select(order.id)) %>%
  
  # Reorder columns
  select(contains("date"), contains("id"), contains("order"),
         quantity, price, total.price,
         everything()) %>%
  
  # Renaming columns
  rename(order_date = order.date) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_")) 

bikes_orderlines_wrangled_tbl %>% glimpse()
```
# 6.0 Business Insights ----
# 6.1 Sales by Year ----
# Step 1 - Manipulate
```{r}
sales_by_year_tbl <- bikes_orderlines_wrangled_tbl %>%
    
    # Selecting columns to focus on and adding a year column
    select(order_date, total_price) %>%
    mutate(year = year(order_date)) %>%
    
    # Grouping by year, and summarizing sales
    group_by(year) %>%
    summarize(sales = sum(total_price)) %>%
    ungroup() %>%
    
    # $ Format Text
    mutate(sales_text = scales::dollar(sales))
    
sales_by_year_tbl
```
# Step 2 - Visualize
```{r}
sales_by_year_tbl %>%
    
    # Setup canvas with year (x-axis) and sales (y-axis)
    ggplot(aes(x = year, y = sales)) +
    
    # Geometries
    geom_col(fill = "#2c3e50") +
    geom_label(aes(label = sales_text)) +
    geom_smooth(method = "lm", se = FALSE) +
    
    # Formatting
    theme_tq() +
    scale_y_continuous(labels = scales::dollar) +
    labs(
        title = "Revenue by Year",
        subtitle = "Upward trend",
        x = "",
        y = "Revenue"
    )
```
# 6.2 Sales by Year and Category 2 ----
# Step 1 - Manipulate
```{r}
sales_by_year_cat_2_tbl <- bikes_orderlines_wrangled_tbl %>%
    
    # Selecting columns and add a year
    select(order_date, total_price, category_2) %>%
    mutate(year = year(order_date)) %>%
    
    # Groupby and Summarize year and category 2
    group_by(year, category_2) %>%
    summarise(sales = sum(total_price)) %>%
    ungroup() %>%
    
    # Format $ Text
    mutate(sales_text = scales::dollar(sales))

sales_by_year_cat_2_tbl
```
# Step 2 - Visualize
```{r}
p = sales_by_year_cat_2_tbl %>%
    
    # Set up x, y, fill 
    ggplot(aes(x = year, y = sales, fill = category_2)) +
    
    # Geometries
    geom_col() +
    geom_smooth(method = "lm", se = FALSE) +
    
    # Facet
    facet_wrap(~ category_2, ncol = 3, scales = "free_y") +
    
    # Formatting
    theme_tq() +
    scale_fill_tq() +
    scale_y_continuous(labels = scales::dollar) +
    labs(
        title = "Revenue by Year and Category 2",
        subtitle = "Each product category has an upward trend",
        x = "",
        y = "Revenue",
        fill = "Product Secondary Category"
    )
p
#
pdf("ggplot.pdf")
print(p)
dev.off()

#
ggsave("myplot.pdf")
ggsave("myplot.png")
ggsave("myplot.png",plot = p)
```
# 7.0 Writing Files ----
```{r}
fs::dir_create("data_wrangled_student")
```
# 7.1 Excel ----
```{r}
bikes_orderlines_joined_tbl %>%
    write_xlsx("data_wrangled_student/bike_orderlines.xlsx")
```
# 7.2 CSV ----
```{r}
bikes_orderlines_joined_tbl %>%
    write_csv("data_wrangled_student/bike_orderlines.csv")
```
# 7.3 RDS ----
```{r}
bikes_orderlines_joined_tbl %>%
    write_rds("data_wrangled_student/bike_orderlines.rds")
```


#作業2
```{r}
day.price = read.table("C:/gittest/01/0506/price_2010_2018_daily.txt")
day.price<-day.price[,-2]
colnames(day.price)<-c("id","","","date","close")
head(day.price)
```

```{r}
library(data.table)
dayprice.reorder = dcast(day.price, date~id)
dim(dayprice.reorder)
head(dayprice.reorder)
```

```{r}
write_rds(dayprice.reorder, "day_price.rds")
```

